sudo: required
language: generic
services:
  - docker

before_install:
  -  docker build -t deepavaliing/dockertravisreact -f Dockerfile.dev .

script:
  -  docker run -e CI=true deepavaliing/dockertravisreact npm run test -- --coverage
  