sudo: required
services:
  - docker

before_install:
  -  docker build -t deepavaliing/dockertravisreact -f Dockerfile.dev .

script:
  -  docker run deepavaliing/dockertravisreact npm run test -- --coverage
  