sudo: required
language: generic
services:
  - docker

before_install:
  -  docker build -t deepavaliing/dockertravisreact -f Dockerfile.dev .

script:
  -  docker run -e CI=true deepavaliing/dockertravisreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-333447488889"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: 
    secure: "AKIAU3IYE4V43VS4DVQ4"
  secret_access_key:
    secure: "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"
