sudo: required
language: generic
services:
  - docker

before_install:
  -  docker build -t deepavaliing/dockertravisreact -f Dockerfile.dev .

script:
  -  docker run -e CI=true deepavaliing/dockertravisreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Dockereact"
  env: "Dockereact-env"
  bucket_name: "elasticbeanstalk-us-east-1-333447488889"
  bucket_path: "Dockereact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
